# Generated by Django 5.2.7 on 2026-02-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_daycarereview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DaycareReview',
        ),
    ]
